name: Build
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Build package
        run: |
          git fetch --prune --unshallow --tags --force
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl
          retention-days: 30
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
